### ISSUE TITLE
Apply theme color to Tiddloid system bars not working

### ISSUE THREAD

**Issue by hubertgk** [donmor/TiddloidLite#12]
Hi Donmor,

I've set the tiddler "$:/config/Tiddloid/ApplyTheme" to "yes" but the theme is not reflected in Tiddloid system bars.

I'm setting my theme by CSS (filter:invert, hue-rotate, etc.) which is probably not the "official" way of switching to dark mode.

**Please let us know what Tiddloid is looking at to determine its theme colour? Is it a specific tiddler, field or index?**

Thank you.

**Comment by donmor** [comment]
Firstly fetch the content of `$:/palette`, for example, `$:/palettes/Vanilla`, and fetch the line `page-background: `, which supports`#******` and `rgb(*,*,*)` format.

**Comment by hubertgk** [comment]
Thank you, it worked perfectly. Closing issue.
