### ISSUE TITLE
Provide the app via Google PlayStore 

### ISSUE THREAD

**Issue by mikegr** [donmor/TiddloidLite#2]
For most users it's much safer to install only apps from the official store. There the code is checked for malicious code and no regular user should need to allow apps to be side-loaded. 

Although the code seems to be GPLv2, 
there is nothing speaking against it to distribute it via the PlayStore. If I remember correctly you only need to provide everything that someone can create the APK themselves. The signing key is essentially not necessary to check the output of the build process. You can even add a donation button or in-app-purchase and are still in alignment with the license.

With GitHub Action that should even be  automatable very easily. 

Please discuss what speaks against it except the obvious effort to set it up accordingly.

**Comment by donmor** [comment]
Hey mikegr,
you know I'm in China and have trouble accessing Google and Play Store. That's why I uploaded the app to the CoolApk, a market in China that I can upload something without paying for anything.

**Comment by sonukuldeep** [comment]
Can you upload it to f-droid? It's similiar to google play store but mostly for open source apps. It could help us stay up-to-date with every new realise too.

**Comment by donmor** [comment]
I tried it before, posting a request on the f-droid page on gitlab, but got eventually no result. ヽ（・＿・；)ノ

**Comment by TheDcoder** [comment]
@donmor Thanks for the great app, however I have to admit that I feel uncomfortable getting the app from "CoolAPK". Please consider uploading your own builds to GitHub by using their releases feature :)

**Comment by TheDcoder** [comment]
I just [bumped](https://gitlab.com/fdroid/rfp/-/issues/986#note_331394327) @donmor's request for inclusion in the F-Droid repository, I hope they include it soon :)

**Comment by TheDcoder** [comment]
[Update](https://gitlab.com/fdroid/rfp/-/issues/986#note_331504657): Looks like there are a few outstanding tasks that need to be completed before F-droid staff can include it in their repository.

**Comment by donmor** [comment]
> @donmor Thanks for the great app, however I have to admit that I feel uncomfortable getting the app from "CoolAPK". Please consider uploading your own builds to GitHub by using their releases feature :)

Hello TheDcoder,
I have had them uploaded before. Just go and check it. 
donmor

**Comment by TheDcoder** [comment]
Hi @donmor, good to see a response from you, hope you are doing well!

Thanks a ton for uploading the APK packages.

> I have had them uploaded before.

I see, I may have perhaps made some mistake, but I was sure that I did not see those assets in GitHub releases when I made my comment. In any case, good to have an alternate source of binaries... if you have the time, please try to update your code so that it can be included in F-droid :)
