### ISSUE TITLE
Publish app to F-Droid repository

### ISSUE THREAD

**Issue by TheDcoder** [donmor/TiddloidLite#3]
Hi,

Thanks for the great work on the app, I like it. However I do not like the fact that the only source of binary builds is CoolApk. So I have opened a request for this app's inclusion in the official F-Droid repository: https://gitlab.com/fdroid/rfp/-/issues/1327

Please also consider hosting your own binary builds on GitHub using their releases feature.

P.S There is already an another request for the original Tiddloid app, this request is for the Lite version.

**Comment by donmor** [comment]
There are already release builds on GitHub. 
Btw F-droid resigns the apk, causing users with old version of apps cannot upgrade to the latest, unless they uninstall the apps, losing all data.

**Comment by TheDcoder** [comment]
I respect your decision. However I would like to point out that there are several benefits of making this app available in the F-Droid repository, the most obvious benefit is the exposure... and users will also have an easier time updating due to having a single store app.

> Btw F-droid resigns the apk

Sort of true. As I understand it, they build the apps from source and use their own key to sign the final package (APK), and like any design decision, this approach has its own pros and cons.

> causing users with old version of apps cannot upgrade to the latest, unless they uninstall the apps, losing all data.

You are right, but since a tiddlywiki is mostly standalone, this shouldn't be a big problem... and not to mention that it is a one-time process. Users who don't want to use F-Droid can just use your own releases on GitHub :smile:

**Comment by donmor** [comment]
I see. Btw does F-droid build apks from the latest commit of master, or the latest tag/release?

**Comment by TheDcoder** [comment]
I am not really familiar with their release policy and build system, but it is reasonable to assume that they build according to the tags in the repository, so each new tag ("releases" as GitHub calls them) should trigger the build of a new version in F-Droid.

**Comment by donmor** [comment]
Okay. Maybe I could have a try later.

**Comment by ritzmann** [comment]
Just wanted to mention that F-Droid was the first place I went looking for TiddloidLite since that is the place where I get all my open source apps from. Maybe you could still find the time to resolve the outstanding issues mentioned in https://gitlab.com/fdroid/rfp/-/issues/1327 ?
