### ISSUE TITLE
[Feature] Support nodejs wiki and github backend

### ISSUE THREAD

**Issue by linonetwo** [donmor/TiddloidLite#4]
Hi, I'm creating https://github.com/tiddly-gittly/TiddlyGit-Desktop/

I now hope there can be a version that can run in my phone, and have memento database style desktop widgets.

Can I modify this TiddloidLite to support nodejs wiki easily?

**Comment by donmor** [comment]
No problem. Just do it.
Remember to use gplv2 if Tiddloid/Lite code used.
BTW avoid to create PRs this year since my PC is down and cannot test the modification. Just build a new app.
