### ISSUE TITLE
Display LaTeX

### ISSUE THREAD

**Issue by Anacletus** [donmor/TiddloidLite#5]
Thanks for this wonderful app.

Using the plugin:

https://github.com/joerenes/TW5-TeXZilla

One can write LaTeX text in a tiddler, and is rendered great using Firefox.
Opening the same wiki in TiddloidLite, LaTeX ins not rendered.

**Comment by donmor** [comment]
On the Texzilla plugin demo page it writes:

>Requirements
>Only Firefox and Safari support MathML at the moment, so the plugin is only useful if you're using one of these browsers. It might be possible to combine this plugin with MathJax to convert MathML to something that other browsers can understand, e.g. HTML+CSS, but I haven't tried this.

Tiddloid series uses webview that implements chromium. It is said that a project called MathJax works, later I'll test it.

**Comment by donmor** [comment]
You can try this plugin:
[MathJax for TW5](http://mathjax-tw5.kantorsite.net/) 

Tested to work, popping Javascript error window though.
