### ISSUE TITLE
Optionally hide top bar once wiki file was loaded

### ISSUE THREAD

**Issue by hubertgk** [donmor/TiddloidLite#6]
Hi Donmor,

First of all, thank you for developing and maintaining this amazing app.

I'd like to make a suggestion regarding the top bar: when a wiki file has been loaded, the top bar remains visible just to show the back arrow. We can already go "back" using Android's system back button, so having a back button in the top bar is repeated functionality.

![Screenshot](https://user-images.githubusercontent.com/25121125/95069104-2197fa00-06fe-11eb-9a93-51026000927b.png)

If there was a setting to optionally hide this bar once wiki was loaded we could reclaim a lot of screen real estate to display more of the wiki content itself.

Please consider this suggestion.
Again, thank you very much for your work on the app, it's extremely useful.

Regards.

**Comment by donmor** [comment]
Now is in progress and available in next update.
