### ISSUE TITLE
Strange behaviour when storing on google drive

### ISSUE THREAD

**Issue by uiorean** [donmor/TiddloidLite#7]
Just wanted to share a problem I have managed to solve:

When google drive is not allowed to run in background on android, Tiddloid Lite will have strange behaviours, such as unable to create, access or re-access tiddlywiki files, although occasionally it does work. 

Google drive must be allowed to run in the background.

**Comment by donmor** [comment]
Are you using a customized Android OS? For me it is Flyme 8 which prevent my nutstore app from waking up when my phone starts up. My solution is to start the app once and then run Tiddloid Lite.

**Comment by uiorean** [comment]
I have configured the phone intentionally to not allow background running of Google Drive so I was at fault here.
